##### CRITICAL #####
# Unexploitable
CVE-2023-45853	# MiniZip zipOpenNewFileInZip4_64
CVE-2022-37434	# zlib inflateGetHeader
CVE-2022-2068	# OpenSSL c_rehash
CVE-2022-1292	# OpenSSL c_rehash
CVE-2024-5535	# OpenSSL ssl_select_next_proto NPN/ALPN
CVE-2021-3711	# OpenSSL EVP_PKEY_decrypt
CVE-2023-38408	# ssh-agent
CVE-2025-5914	# libarchive archive_read_format_rar_seek_data
CVE-2019-12900	# bzip2 BZ2_decompress

# False positives
CVE-2005-2541	# tar, fixed in 1.15
CVE-2023-37920	# ca-certificates, fixed in 2023
CVE-2019-19814	# fixed in kernel 5.0.21
CVE-2025-32463	# Android, sudo -R/--chroot, fixed

## TeslaOS
CVE-2024-38612	# kernel 5.4

# Possibly but unlikely from GUI apps
CVE-2025-4517	# python tarfile.extractall
CVE-2022-48565	# python plistlib, XXE
CVE-2007-4559	# python extractall
CVE-2023-47100	# perl S_parse_uniprop_string, RCE, DoS

# Possibly exploitable
CVE-2022-3515	# GPG (Libksba), RCE
CVE-2025-49794	# libxml2 xmlSchematronGetNode, DoS, undef behav.
CVE-2025-49796
CVE-2021-46848	# libtasn1 asn1_encode_simple_der, out-of-bounds read
CVE-2025-6965	# SQLite, memory corruption
CVE-2025-29088	# SQLite, DoS
CVE-2021-3520	# lz4, out-of-bounds write
CVE-2018-13410	# Info-Zip zip 3.0, DoS

## TeslaOS
CVE-2024-38541	# kernel < 6.6.33
CVE-2021-47378	# kernel < 5.10.70
CVE-2021-3773	# kernel < 5.14
CVE-2024-47685	# kernel < 5.14
