##### HIGH #####
# Unexploitable
CVE-2025-32462	# sudo allows remote host RCE
CVE-2023-2650	# Android Openssl OBJ_obj2txt, DoS

# Unlikely
CVE-2025-26465	# Android, OpenSSH MITM, impersonating
CVE-2023-48795  # Android, OpenSSH
CVE-2024-32002	# Android, git hook, RCE
CVE-2022-48522 	# Android, Perl S_find_uninit_var, RCE, LPE

# False positives
CVE-2019-5736	# Android, runc 1.0-rc6
CVE-2023-0286	# Android openssl, Leak, DoS, fixed
CVE-2024-6119  #fixed ✔
CVE-2022-40735 #fixed ✔
CVE-2023-5363  #fixed ✔
CVE-2022-3358  #fixed ✔
CVE-2025-3277	# Android, concat_ws not present

# Possibly
CVE-2022-1271	# xzgrep, RCE
CVE-2021-23240	# SELinux sudo, LPE
CVE-2023-26604	# systemd configuration, sudo, less, LPE
CVE-2023-22809	# sudo -e EDITOR, LPE
CVE-2021-3156	# sudoedit -s, LPE
CVE-2022-3602	# After certificate chain signature verification and
	# requires either a CA to have signed the malicious certificate or
	# for the application to continue certificate verification despite
	# failure to construct a path to a trusted issuer.
	# An attacker can craft a malicious email address to overflow
	# four attacker-controlled bytes on the stack
CVE-2025-1094	# Android PostgreSQL, SQL injection


# Android
CVE-2022-3786	# Android, openssl, fixed in 2025.10
CVE-2023-4807	# Android, openssl, affects Windows only

# Not-installed by default
## TeslaOS
CVE-2023-44431	# bluez, RCE


# CVE-2023-50387	# DNSSEC, DoS
# CVE-2025-4598		# systemd, LPE
# CVE-2022-25315, CVE-2022-22822	# libexpat, IOF
# CVE-2020-17541	# libjpeg-turbo, RCE, DoS
# CVE-2020-14152	# libjpeg, DoS