##### MEDIUM #####

# Possibly
CVE-2025-45582	# tar, directory traversal, AutoSD, Android

# Unlikely
CVE-2025-25724	# libarchive list_item_verbose, Undefined Behavior
CVE-2025-5915	# libarchive copy_from_lzss_window, buffer over-read
CVE-2025-5916	# libarchive _warc_rdhdr integer overflow, when processing a Web Archive (WARC) file that claims to have more than INT64_MAX - 4 content bytes
CVE-2025-5918	# libarchive file_skip, buffer over-read
