#!/bin/bash
################################################################################
# @file      read-report
# @brief     Read reports generated by Grype, CBT, Vanir, Yocto, VERA
# @date      Mo Jul 2025
# @author    Dimitri Simon
# 
# PROJECT:   VERA
# 
# MODIFIED:  Tue Jul 08 2025
# BY:        Dimitri Simon
# 
# Copyright (c) 2025 Dimitri Simon
# 
################################################################################

# usage:
# read-report.sh <file> [--filter-out-impact <impact>] [<state> [<full>]]
#   state: boolean (default: true)
#   full: boolean (default: true)

if [[ -z "$1" || ! -f "$1" ]]; then
	exit 1
fi


join_by() {
	local d=${1-} f=${2-}
	if shift 2; then
		printf %s "$f" "${@/#/$d}"
	fi
}


POSITIONAL_ARGS=()
FILTER_OUT_IMPACT=

while [[ $# -gt 0 ]]; do
  case $1 in
    -f|--filter-out-impact)
      FILTER_OUT_IMPACT="$2"
      shift 2 # past argument, past value
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      POSITIONAL_ARGS+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done

# echo "FILTER_OUT_IMPACT: $FILTER_OUT_IMPACT"

set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters


filepath="$1"
filter_state='#'
filter_full=
show_state=':\(.state)'
show_full=':\(.name)\((.version // "") | if . != "" then "=" + . else "" end):\(.ecosystem)'
sort_unique_args="-k5,5"


if [ "${2:-1}" = false ] || [ "${2:-1}" -eq 0 ]; then
	filter_state=
	show_state=
fi

if [ "${3:-1}" = false ] || [ "${3:-1}" -eq 0 ]; then
	filter_full='#'
	show_full=':\(.name):\(.ecosystem)'
	# sort_unique_args=-k3,3
fi

read_report() {
	jq -r --arg FILTER_OUT_IMPACT "$FILTER_OUT_IMPACT" '
def trunc_to(n):
    # Convert to string, keep only up to n decimal digits
    tostring
    | capture("(?<int>-?[0-9]+)(?:\\.(?<frac>[0-9]{0," + (n|tostring) + "}))?")
    | if .frac then "\(.int).\(.frac)" else .int end
    | tonumber;
def normalize_impact($v):
  ($v // "")
  | gsub("(?i)(^|,)[[:space:]]*unknown[[:space:]]*(,|$)"; "")
  | gsub("^[[:space:],]+|[[:space:],]+$"; "");

def impact_from_vector($v):
  normalize_impact($v) as $clean
  | ($clean | ascii_downcase) as $s

  | if ($s == "") then
      "?"

    elif ($s == "eop") then
      "LPE"

    elif ($clean | test(":")) then
      if (
        ($clean | test("AV:(N|A)"))			# Network or Adjacent
        and ($clean | test("PR:H") | not)	# No High Privileges
# 		# and test("UI:N")					# Might require User Interaction
        and ($clean | test("C:H|I:H"))		# High Confidentiality or Integrity impact
      ) then "RCE"

      elif (
        ($clean | test("PR:H") | not)		# No High Privileges
        and ($clean | test("C:H"))			# High Confidentiality impact
        and ($clean | test("I:H"))			# High Integrity impact
      ) then "LPE"

      elif (
        ($clean | test("A:H"))				# High Availability impact
        and ($clean | test("C:H|I:H") | not) # No Confidentiality or Integrity impact
      ) then "DoS"

      elif (
        ($clean | test("C:H"))
      ) then "ID"

      else "?"
      end

    else
      $clean
    end;

	'"$1"'
		# | map(. + {
		# 	risk: (.epss * (.cvss | tonumber?)) | trunc_to(4)
		# })
		| map(. + {
			impact: impact_from_vector(.impact)
		})
		| group_by(.cveId)[]
		| max_by(.cvss)
		'"$filter_state"'| select((.state // "") != "fixed")
		# | select(
		# 	(.impact // "" | ascii_downcase) as $s
		# 	| ($FILTER_OUT_IMPACT | split(",") | map(ascii_downcase))
		# 	| index($s)
		# 	| not
		# )
		| "\(.cvss):\(.epss)'"$show_full"':\(.cveId):\(.impact):\(.kev // "")'"$show_state"'"' \
	"$filepath" | sort $sort_unique_args -u -t:
}

# OSV-Scanner
if jq -e '
  type == "object"
  and has("results")
  and (.results | type == "array")
  and all(.results[]; has("packages"))
' "$filepath" &> /dev/null; then
	read_report '[
	.results[]?.packages[]? as $pkg |
	$pkg.groups[]? as $group |
	$group.aliases[]? | select(startswith("CVE-")) as $cve |
	{
		name: ($pkg.package.name // "" | gsub(":"; "-") | 
		if contains("/") then
			(split("/") | (if length >= 2 then ".../" + .[-2] + "/" + .[-1] else .[-1] end))
		else .
		end),
		'$filter_full'version: ($pkg.package.version // "" | sub("[+\\-~].*"; "")),
		ecosystem: ($pkg.package.ecosystem // "" | gsub(":"; "-")),
		cveId: $cve,
		cvss: (
			if ($group.max_severity // "" | length) == 0 then -1
			else ($group.max_severity | tonumber)
			end
		),
		epss: -1
	}
	]
	' "$filepath" | sort -u

# CVE Binary Tool
elif jq -e 'type == "array" and all(.[]; has("paths"))' "$filepath" &> /dev/null; then
	# echo CBT
	read_report '[
	.[] as $pkg |
	{
		name: ($pkg.product // "" | gsub(":"; "-") | 
			if contains("/") then
				(split("/") | (if length >= 2 then ".../" + .[-2] + "/" + .[-1] else .[-1] end))
			else .
			end
		),
		'$filter_full'version: ($pkg.version // "" | sub("[+\\-~].*"; "")),
		ecosystem: ($pkg.vendor // "" | gsub(":"; "-")),
		cveId: $pkg.cve_number,
		cvss: (
			if ($pkg.score // "unknown") == "unknown" then -1
			else ($pkg.score | tonumber)
			end
		),
		epss: (($pkg.epss_probability // -1)
			| tonumber?
			| if type == "string" then 0.0001 
			elif . == null or . < 0 then -1
			elif . < 0.0001 then 0.0001
			elif . > 1.0 then 0.0001
			else . | trunc_to(4)
			end
		),
		percentile: (($pkg.epss_percentile // -1) | tonumber),
		state: "",
		impact: ($pkg.cvss_vector // "")
	}
	]'

# Grype
elif jq -e 'type == "object" and has("matches")' "$filepath" &> /dev/null; then
	# echo Grype
	read_report '
		[
			(
				.matches[]?        | . + {__default_state: ""},
				.ignoredMatches[]? | . + {__default_state: "fixed"}
			) as $match |
			$match.matchDetails[]? as $grp |
			{
				name: ($grp.searchedBy.package.name // "" | gsub(":"; "-") | 
					if contains("/") then
						(split("/") | (if length >= 2 then ".../" + .[-2] + "/" + .[-1] else .[-1] end))
					else .
					end
				),
				'$filter_full'version: ($grp.searchedBy.package.version // "" | sub("[+\\-~].*"; "")),
				ecosystem: (
					if $grp.searchedBy.distro? 
					then (($grp.searchedBy.distro.type // "") + "-" + ($grp.searchedBy.distro.version // "")) 
						| gsub(":"; "-")
					else null 
					end
				),
				vendor: (
					if ($grp.searchedBy.cpes[0]? | type) == "string" 
					then ($grp.searchedBy.cpes[0] | split(":")[3]) 
					else null 
					end
				),
				cveId: $match.vulnerability.id,
				cvss: (
					[
						(try $match.vulnerability.cvss[0].metrics.baseScore catch ""),
						(try $match.relatedVulnerabilities[]?.cvss[0].metrics.baseScore catch "")
					]
					| map(select(. != null))
					| max?
				),
				epss: (
					[
						(try $match.vulnerability.epss[]?.epss // ""),
						(try $match.relatedVulnerabilities[]?.epss[]?.epss // "")
					]
					| map(select(. != null))
					| max?           # pick the highest EPSS value
				),
				percentile: (
					[
						(try $match.vulnerability.epss[]?.percentile // ""),
						(try $match.relatedVulnerabilities[]?.epss[]?.percentile // "")
					]
					| map(select(. != null))
					| max?           # pick the highest percentile value
				),
				state: ($match.vulnerability.fix?.state // $match.__default_state),
				impact: (
					$match.vulnerability?.cvss?[0]?.vector
					//
					$match.relatedVulnerabilities[]?.cvss?[0]?.vector
					//
					""
				)
			}
		]
	'

# Trivy
elif jq -e 'type == "object" and all(.Results[]; has("Target"))' "$filepath" &> /dev/null; then
	# echo Trivy
	jq -sr '
	[ (.. | objects | select(has("VulnerabilityID"))) as $v
		| {
			cveId: $v.VulnerabilityID,
			cvss: (
				[ $v.CVSS?[]? | .V2Score?, .V3Score?, .V4Score? ]
				| map(select(. != null))
				| max // -1
			),
			name: $v.PkgName,
			'$filter_full'version: ($v.InstalledVersion | sub("[-+~].*$"; "")),
			ecosystem: $v.DataSource.ID
		}
	]
	| group_by(.cveId)
	| map(max_by(.cvss))
	# | select((.state // "") != "fixed")
	| "\(.cvss):-1:\(.name)=\(.version):\(.ecosystem):\(.cveId)"
	' "$filepath" | sort -u

# Compressed result
elif jq -e 'all(.[]; has("cveId"))' "$filepath" &> /dev/null; then
	# echo "Compressed"
	read_report '
		[
			.[] as $prod
			| {
				cveId: ($prod.id // $prod.cveId),
				cvss: (
					if ($prod.cvss | type) == "string" then
						{Critical:10, High:7.5, Moderate:5, Low:2.5}[$prod.cvss] // -1
					else
						$prod.cvss // -1
					end
				),
				name: (($prod.name // "") | scan("^[^,;]*") | sub("^platform/.+/"; "")),
				ecosystem: ($prod.ecosystem // $prod.vendor // ""),
				'$filter_full'version: (($prod.version // "") | sub("^[0-9]+:"; "")),
				epss: (
					($prod.epss // -1)
					| tonumber?
					| if type == "string" then 0.0001 
					elif . == null or . < 0 then -1
					elif . < 0.0001 then 0.0001
					elif . > 1.0 then 0.0001
					else . | trunc_to(4)
					end
				),
				percentile: (($prod.percentile // -1) | if . != null then trunc_to(2) else null end),
				state: ($prod.state // ""),
				impact: ($prod.scoring_vector // ""),
				kev: (if $prod.kev then "X" else "" end)
			}
		]
	'

# Vanir
elif jq -e 'all(.missing_patches[]; has("ID"))' "$filepath" &> /dev/null; then
	# echo "Detected: Vanir"
	jq -r '(
		'"$filter_state"'(.covered_cves[] | [-1, -1, "", "", ., "", "", "fixed"]),
		(.missing_patches[].CVE[] | [-1, -1, "", "", .])
		)| join(":")
	' "$filepath"
			
# Yocto's built-in cve-check
elif jq -e 'type == "object" and all(.package[] | .issue[]; has("id"))' "$filepath" &> /dev/null; then
	read_report '[
	.package[]
		| .name as $product
		'$filter_full'| .version as $version
		| .layer as $ecosystem
		| (.issue // [])[]      # handle empty issue arrays
		| {
			cveId: .id,
			epss: -1,
			state: (
				{ "Patched": "fixed",
					"Unpatched": "not-fixed",
					"Ignored": "wont-fix"
				}[.status] // "unknown"
			),
			cvss: (
				[ .scorev4, .scorev3, .scorev2 ]
				| map(tonumber? | select(. != 0))
				| first
			),
			name: $product,
			'$filter_full'version: $version,
			ecosystem: $ecosystem,
			impact: (.vectorString // "")
		}
		]
	'

else
	echo "Error: unknown format for file '$filepath'" >&2
	exit 1
fi